# Generated by Django 5.1.3 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_call_started",
            field=models.BooleanField(default=False),
        ),
    ]
