# Generated by Django 5.1.6 on 2025-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0002_appointment_is_call_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_call_ended",
            field=models.BooleanField(default=False),
        ),
    ]
